spring.application.name=progettofinale



spring.datasource.url=jdbc:h2:file:./h2-db/testdb
spring.datasource.driver-class-name=org.h2.Driver

spring.datasource.username=sa
spring.datasource.password=


spring.jpa.database-platform=org.hibernate.ialect.H2Dialect

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

spring.jpa.defer-datasource-initialization=true

spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data.sql

spring.h2.console.enabled=true